spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sdjavaproject@gmail.com
    password: java@2022
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true